import type { DatabaseDialect } from "../types.ts";
import { assertValidCollection, type CollectionLike } from "./common.ts";
import { buildPostgresTable } from "./postgres.ts";
import { buildSqliteTable } from "./sqlite.ts";

export type { CollectionLike } from "./common.ts";
export { toColumnName } from "./common.ts";

export interface SchemaToTablesOptions {
  /** SQL flavor to emit. D1 uses `"sqlite"`. */
  dialect: DatabaseDialect;
}

// biome-ignore lint/suspicious/noExplicitAny: drizzle's generated table types are wide; consumers narrow via collection slug.
export type GeneratedTables = Record<string, any>;

/**
 * Build Drizzle table definitions from a list of collections/singletons.
 *
 * Every table gets the standard system columns:
 *   - `id`         TEXT primary key (ULID, generated by `@voila/content`)
 *   - `createdAt`  timestamp_ms / timestamptz, NOT NULL, defaults to now()
 *   - `updatedAt`  timestamp_ms / timestamptz, NOT NULL, defaults to now()
 *   - `deletedAt`  timestamp_ms / timestamptz, NULL (soft-delete marker; M2)
 *
 * Singletons additionally carry a `CHECK("id" = '<slug>')` so only a single
 * row can exist.
 *
 * Dispatches to `./sqlite.ts` or `./postgres.ts` based on `dialect`.
 */
export function schemaToTables(
  collections: readonly CollectionLike[],
  options: SchemaToTablesOptions,
): GeneratedTables {
  const out: GeneratedTables = {};
  for (const c of collections) {
    assertValidCollection(c);
    if (out[c.slug]) throw new Error(`schemaToTables: duplicate collection slug "${c.slug}"`);
    out[c.slug] = options.dialect === "sqlite" ? buildSqliteTable(c) : buildPostgresTable(c);
  }
  return out;
}
