/* eslint-disable */
// @ts-nocheck
// This file is generated by TanStack Router. `vite dev` and `vite build`
// regenerate it from the files under `app/routes` — this placeholder just keeps
// `router.tsx`'s import valid before the first run. Do not edit by hand.

import { createRootRoute } from "@tanstack/react-router";

export const routeTree = createRootRoute();

import type { getRouter } from "./router.tsx";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
