import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import type { Plugin, ResolvedConfig } from "vite";
import {
  adminApiByFieldSource,
  adminApiByIdSource,
  adminApiListSource,
  cloudflareEnvDeclSource,
} from "./routes/admin-api.ts";
import { healthRouteSource } from "./routes/admin-api-health.ts";
import { adminIndexSource, adminLayoutSource } from "./routes/admin-layout.ts";
import { adminSetupSource } from "./routes/admin-setup.ts";
import {
  adminCollectionDetailSource,
  adminCollectionListSource,
  adminSingletonSource,
} from "./routes/admin-views.ts";
import type { Content } from "./types.ts";

export type VoilaPluginOptions = {
  /**
   * Path to the `content.config.ts` file, relative to vite's project root.
   * Defaults to `./content.config.ts` (auto-discovery).
   *
   * Pass an already-resolved `Content` object to skip filesystem
   * discovery — useful for multi-tenant setups that build the config
   * dynamically.
   */
  config?: string | Content;
};

const DEFAULT_CONFIG_PATH = "./content.config.ts";
const GENERATED_HEADER =
  "// DO NOT EDIT — generated by @voila/content/vite. Regenerated on `vite dev`.\n";

/**
 * Resolve a relative config path against the project root, accepting either a
 * `.ts` or `.tsx` file. A `.tsx` config lets consumers put JSX in their
 * `defineContent` call (e.g. `branding.logo` as an inline component). When the
 * given path has a `.ts` extension and that file is missing, fall back to the
 * `.tsx` sibling. Returns the primary path unchanged when neither exists so
 * callers can `existsSync`-gate generation.
 */
function resolveConfigPath(root: string, configSource: string): string {
  const primary = resolve(root, configSource);
  if (existsSync(primary)) return primary;
  if (primary.endsWith(".ts")) {
    const tsx = `${primary}x`;
    if (existsSync(tsx)) return tsx;
  }
  return primary;
}

/**
 * The `@voila/content` vite plugin. Add to `vite.config.ts` alongside
 * `tanstackStart()` and the plugin will:
 *
 * - Auto-discover `./content.config.ts` (override via `config: '…'`).
 * - Generate the M0 admin route files (admin shell, setup placeholder,
 *   health server route) into `<root>/src/routes/admin/`. The files are
 *   marked as generated and re-emitted on every dev start; gitignore
 *   `src/routes/admin/` in the consumer.
 */
export function voila(options: VoilaPluginOptions = {}): Plugin {
  const configSource = options.config ?? DEFAULT_CONFIG_PATH;
  let resolved: ResolvedConfig | undefined;

  return {
    name: "@voila/content",
    enforce: "pre",
    api: { configSource },
    configResolved(config) {
      resolved = config;
      if (typeof configSource !== "string") return;
      const configAbsPath = resolveConfigPath(config.root, configSource);
      if (!existsSync(configAbsPath)) return;
      writeAdminRoutes({ root: config.root, configAbsPath });
    },
    configureServer(server) {
      const cfg = resolved;
      if (!cfg || typeof configSource !== "string") return;
      const configAbsPath = resolveConfigPath(cfg.root, configSource);
      server.watcher.on("change", (file) => {
        if (file === configAbsPath) writeAdminRoutes({ root: cfg.root, configAbsPath });
      });
    },
  };
}

function writeAdminRoutes({ root, configAbsPath }: { root: string; configAbsPath: string }): void {
  const routesDir = join(root, "src", "routes", "admin");
  const apiDir = join(routesDir, "api");
  mkdirSync(apiDir, { recursive: true });

  const configImportFrom = (file: string) => {
    const fromDir = dirname(file);
    const noExt = configAbsPath.replace(/\.tsx?$/, "");
    let rel = relative(fromDir, noExt).replace(/\\/g, "/");
    if (!rel.startsWith(".")) rel = `./${rel}`;
    return rel;
  };

  const layoutFile = join(root, "src", "routes", "admin.tsx");
  const indexFile = join(routesDir, "index.tsx");
  const splatFile = join(routesDir, "$.tsx");
  const setupFile = join(routesDir, "setup.tsx");
  const collectionListFile = join(routesDir, "collections.$collection.index.tsx");
  const collectionDetailFile = join(routesDir, "collections.$collection.$id.tsx");
  const singletonFile = join(routesDir, "singletons.$singleton.tsx");
  const healthFile = join(apiDir, "health.ts");
  const listFile = join(apiDir, "$collection.ts");
  const byIdFile = join(apiDir, "$collection.$id.ts");
  const byFieldFile = join(apiDir, "$collection.by.$field.$value.ts");

  // Drop a stale `admin/$.tsx` from older generations. The splat used to be
  // the entry point; now `admin.tsx` is the layout and the index sits at
  // `admin/index.tsx`. Leaving the splat in place creates an ambiguous match
  // for `/admin` (both `/admin/$` and `/admin/` resolve there after trailing-
  // slash normalization), which TanStack warns about on every navigation.
  if (existsSync(splatFile)) rmSync(splatFile);

  writeIfChanged(
    layoutFile,
    `${GENERATED_HEADER}${adminLayoutSource(configImportFrom(layoutFile))}`,
  );
  writeIfChanged(indexFile, `${GENERATED_HEADER}${adminIndexSource(configImportFrom(indexFile))}`);
  writeIfChanged(setupFile, `${GENERATED_HEADER}${adminSetupSource(configImportFrom(setupFile))}`);
  writeIfChanged(
    collectionListFile,
    `${GENERATED_HEADER}${adminCollectionListSource(configImportFrom(collectionListFile))}`,
  );
  writeIfChanged(
    collectionDetailFile,
    `${GENERATED_HEADER}${adminCollectionDetailSource(configImportFrom(collectionDetailFile))}`,
  );
  writeIfChanged(
    singletonFile,
    `${GENERATED_HEADER}${adminSingletonSource(configImportFrom(singletonFile))}`,
  );
  writeIfChanged(healthFile, `${GENERATED_HEADER}${healthRouteSource()}`);
  writeIfChanged(listFile, `${GENERATED_HEADER}${adminApiListSource(configImportFrom(listFile))}`);
  writeIfChanged(byIdFile, `${GENERATED_HEADER}${adminApiByIdSource(configImportFrom(byIdFile))}`);
  writeIfChanged(
    byFieldFile,
    `${GENERATED_HEADER}${adminApiByFieldSource(configImportFrom(byFieldFile))}`,
  );

  // The generated API routes import the `cloudflare:workers` virtual module.
  // Ship an ambient declaration so they type-check out of the box — but only
  // when the consumer hasn't generated their own via `wrangler types`, since
  // two `declare module "cloudflare:workers"` blocks would clash.
  //
  // The `-` prefix keeps TanStack's file-router from treating this `.d.ts` as a
  // route (it matches the default `routeFileIgnorePrefix`); TypeScript still
  // picks it up since ambient declarations are name-agnostic.
  if (!existsSync(join(root, "worker-configuration.d.ts"))) {
    writeIfChanged(
      join(routesDir, "-cloudflare-env.d.ts"),
      `${GENERATED_HEADER}${cloudflareEnvDeclSource()}`,
    );
  }
}

function writeIfChanged(file: string, contents: string): void {
  if (existsSync(file) && readFileSync(file, "utf8") === contents) return;
  writeFileSync(file, contents);
}
