import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import type { Plugin, ResolvedConfig } from "vite";
import { healthRouteSource } from "./routes/admin-api-health.ts";
import { adminSetupSource } from "./routes/admin-setup.ts";
import { adminSplatSource } from "./routes/admin-splat.ts";
import type { Content } from "./types.ts";

export type VoilaPluginOptions = {
  /**
   * Path to the `content.config.ts` file, relative to vite's project root.
   * Defaults to `./content.config.ts` (auto-discovery).
   *
   * Pass an already-resolved `Content` object to skip filesystem
   * discovery — useful for multi-tenant setups that build the config
   * dynamically.
   */
  config?: string | Content;
};

const DEFAULT_CONFIG_PATH = "./content.config.ts";
const GENERATED_HEADER =
  "// DO NOT EDIT — generated by @voila/content/vite. Regenerated on `vite dev`.\n";

/**
 * The `@voila/content` vite plugin. Add to `vite.config.ts` alongside
 * `tanstackStart()` and the plugin will:
 *
 * - Auto-discover `./content.config.ts` (override via `config: '…'`).
 * - Generate the M0 admin route files (admin shell, setup placeholder,
 *   health server route) into `<root>/src/routes/admin/`. The files are
 *   marked as generated and re-emitted on every dev start; gitignore
 *   `src/routes/admin/` in the consumer.
 */
export function voila(options: VoilaPluginOptions = {}): Plugin {
  const configSource = options.config ?? DEFAULT_CONFIG_PATH;
  let resolved: ResolvedConfig | undefined;

  return {
    name: "@voila/content",
    enforce: "pre",
    api: { configSource },
    configResolved(config) {
      resolved = config;
      if (typeof configSource !== "string") return;
      const configAbsPath = resolve(config.root, configSource);
      if (!existsSync(configAbsPath)) return;
      writeAdminRoutes({ root: config.root, configAbsPath });
    },
    configureServer(server) {
      const cfg = resolved;
      if (!cfg || typeof configSource !== "string") return;
      const configAbsPath = resolve(cfg.root, configSource);
      server.watcher.on("change", (file) => {
        if (file === configAbsPath) writeAdminRoutes({ root: cfg.root, configAbsPath });
      });
    },
  };
}

function writeAdminRoutes({ root, configAbsPath }: { root: string; configAbsPath: string }): void {
  const routesDir = join(root, "src", "routes", "admin");
  const apiDir = join(routesDir, "api");
  mkdirSync(apiDir, { recursive: true });

  const configImportFrom = (file: string) => {
    const fromDir = dirname(file);
    const noExt = configAbsPath.replace(/\.tsx?$/, "");
    let rel = relative(fromDir, noExt).replace(/\\/g, "/");
    if (!rel.startsWith(".")) rel = `./${rel}`;
    return rel;
  };

  const splatFile = join(routesDir, "$.tsx");
  const setupFile = join(routesDir, "setup.tsx");
  const healthFile = join(apiDir, "health.ts");

  writeIfChanged(splatFile, `${GENERATED_HEADER}${adminSplatSource(configImportFrom(splatFile))}`);
  writeIfChanged(setupFile, `${GENERATED_HEADER}${adminSetupSource(configImportFrom(setupFile))}`);
  writeIfChanged(healthFile, `${GENERATED_HEADER}${healthRouteSource()}`);
}

function writeIfChanged(file: string, contents: string): void {
  if (existsSync(file) && readFileSync(file, "utf8") === contents) return;
  writeFileSync(file, contents);
}
