import { createRouter as createTanStackRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

// The app router. `routeTree.gen` is generated by the TanStack Start plugin
// from the files under `app/routes` — run `vite dev` once and it appears.
export function getRouter() {
  return createTanStackRouter({
    routeTree,
    scrollRestoration: true,
  });
}
