import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { AnyCollection, AnySingleton, Content } from "@voila/content";
import type { DatabaseDialect } from "@voila/content-database";
import type { AnyFieldDef } from "@voila/content-schema";

const GENERATED_HEADER =
  "// DO NOT EDIT — generated by `voila schema generate`. Regenerated on every run.\n";

export interface WriteBridgeOptions {
  /** Absolute path of the project root (`cwd`). */
  cwd: string;
  /** Absolute path of the loaded `content.config.ts`. Unused at codegen
   *  time (the bridge is self-contained) but kept for parity with prior
   *  signatures so callers don't have to change. */
  configAbsPath: string;
  /** Where the bridge file will be written. */
  bridgeAbsPath: string;
  /** Pre-loaded content used to enumerate slugs + fields. */
  content: Content;
  /** Dialect we're emitting for; picks sqliteTable vs pgTable + per-field types. */
  dialect: DatabaseDialect;
}

/**
 * Write the bridge schema file that drizzle-kit consumes.
 *
 * The bridge is **self-contained**: rather than calling `schemaToTables` at
 * runtime against the user's `content.config.ts`, we emit literal Drizzle
 * table definitions per slug. That gives:
 *   - full column-level type inference on each export
 *     (`SQLiteTableWithColumns<{ name: 'posts'; columns: { title: …; … } }>`)
 *   - no runtime dependency on `content.config.ts` from the bridge — drizzle-kit
 *     consumes the file without evaluating user code
 *   - identical DDL output to the runtime path (`schemaToTables`), since both
 *     end up producing the same Drizzle table objects
 *
 * Idempotent: rewriting an identical file is a no-op so file watchers don't
 * see spurious changes.
 */
export function writeDrizzleBridge(options: WriteBridgeOptions): void {
  const { content, dialect, bridgeAbsPath } = options;
  const dir = dirname(bridgeAbsPath);
  mkdirSync(dir, { recursive: true });

  const all: ReadonlyArray<AnyCollection | AnySingleton> = [
    ...content.collections,
    ...content.singletons,
  ];

  // Validate up-front so codegen errors surface here rather than as a drizzle
  // failure later. Mirrors the runtime assertion in `schemaToTables`.
  for (const c of all) assertValidForCodegen(c);

  if (all.length === 0) {
    writeIfChanged(
      bridgeAbsPath,
      `${GENERATED_HEADER}\n// no collections defined yet\nexport {};\n`,
    );
    return;
  }

  // Walk every table emission first so we can collect the exact set of
  // drizzle-orm helpers each output references. Then emit only those imports
  // — otherwise editor lints (and `noUnusedImports`) flag `real` / `boolean`
  // / `date` / `jsonb` whenever a config doesn't happen to use them.
  const used = new Set<string>();
  const tables = all.map((c) => emitTable(c, dialect, used)).join("\n\n");

  const body = `${GENERATED_HEADER}\n${emitImports(dialect, used)}\n\n${tables}\n`;
  writeIfChanged(bridgeAbsPath, body);
}

const IDENT_RE = /^[A-Za-z_][A-Za-z0-9_]{0,59}$/;

function assertValidForCodegen(c: AnyCollection | AnySingleton): void {
  if (!IDENT_RE.test(c.slug)) {
    throw new Error(`writeDrizzleBridge: invalid slug "${c.slug}"`);
  }
  for (const name of Object.keys(c.fields)) {
    if (!IDENT_RE.test(name)) {
      throw new Error(`writeDrizzleBridge: invalid field name "${name}" in collection "${c.slug}"`);
    }
  }
}

/* ---------------------------------------------------------------- imports */

const SQLITE_HELPERS = new Set(["check", "integer", "real", "sqliteTable", "text"]);
const POSTGRES_HELPERS = new Set([
  "boolean",
  "check",
  "date",
  "integer",
  "jsonb",
  "pgTable",
  "real",
  "text",
  "timestamp",
]);

/**
 * Emit the import block, picking only the helpers actually referenced by
 * the generated tables (collected in `used` during table emission).
 *
 * `sql` is always imported because every emission uses it for system column
 * defaults; the table factory (`sqliteTable` / `pgTable`) is likewise always
 * referenced once `used` is non-empty.
 */
function emitImports(dialect: DatabaseDialect, used: Set<string>): string {
  const allowed = dialect === "sqlite" ? SQLITE_HELPERS : POSTGRES_HELPERS;
  const helpers = [...used].filter((u) => allowed.has(u)).sort();
  const path = dialect === "sqlite" ? "drizzle-orm/sqlite-core" : "drizzle-orm/pg-core";
  return [
    `import { sql } from "drizzle-orm";`,
    `import { ${helpers.join(", ")} } from "${path}";`,
  ].join("\n");
}

/* ----------------------------------------------------------------- tables */

function emitTable(
  c: AnyCollection | AnySingleton,
  dialect: DatabaseDialect,
  used: Set<string>,
): string {
  const tableFn = dialect === "sqlite" ? "sqliteTable" : "pgTable";
  used.add(tableFn);

  const systemCols = emitSystemColumns(dialect, used);
  const fields = c.fields as Record<string, AnyFieldDef>;
  const fieldCols = Object.entries(fields).map(
    ([name, field]) => `  ${name}: ${emitColumn(name, field, dialect, used)},`,
  );
  const cols = [...systemCols, ...fieldCols].join("\n");

  const head = `export const ${c.slug} = ${tableFn}(${json(c.slug)}, {\n${cols}\n}`;

  if (c.kind === "singleton") {
    // CHECK must use string-template literals (no `${}` interpolation of the
    // slug value) so drizzle-kit renders it as a SQL literal rather than a
    // bind parameter. Slug is regex-validated above, so embedding it directly
    // into the template is safe.
    used.add("check");
    return `${head}, (t) => [\n  check("${c.slug}_singleton", sql\`\${t.id} = '${c.slug}'\`),\n]);`;
  }
  return `${head});`;
}

function emitSystemColumns(dialect: DatabaseDialect, used: Set<string>): string[] {
  if (dialect === "sqlite") {
    used.add("text").add("integer");
    // Canonical UUID v4 expression in pure sqlite — every table's id defaults
    // to a fresh UUID even for raw SQL inserts. Runtime can still override.
    const uuid =
      "lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)), 2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))";
    return [
      `  id: text("id").primaryKey().default(sql\`(${uuid})\`),`,
      `  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().default(sql\`(unixepoch() * 1000)\`),`,
      `  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().default(sql\`(unixepoch() * 1000)\`),`,
      `  deletedAt: integer("deleted_at", { mode: "timestamp_ms" }),`,
    ];
  }
  used.add("text").add("timestamp");
  return [
    `  id: text("id").primaryKey().default(sql\`gen_random_uuid()\`),`,
    `  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),`,
    `  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),`,
    `  deletedAt: timestamp("deleted_at", { withTimezone: true, mode: "date" }),`,
  ];
}

/* ---------------------------------------------------------------- columns */

function emitColumn(
  name: string,
  field: AnyFieldDef,
  dialect: DatabaseDialect,
  used: Set<string>,
): string {
  const col = toColumnName(name);
  const base =
    dialect === "sqlite" ? emitSqliteBase(col, field, used) : emitPostgresBase(col, field, used);
  return applyMods(base, field);
}

function emitSqliteBase(col: string, field: AnyFieldDef, used: Set<string>): string {
  switch (field.kind) {
    case "string":
      used.add("text");
      return `text(${json(col)})`;
    case "number":
      if ((field as { integer?: boolean }).integer === true) {
        used.add("integer");
        return `integer(${json(col)})`;
      }
      used.add("real");
      return `real(${json(col)})`;
    case "boolean":
      used.add("integer");
      return `integer(${json(col)}, { mode: "boolean" })`;
    case "date":
      used.add("text");
      return `text(${json(col)})`;
    case "datetime":
      used.add("integer");
      return `integer(${json(col)}, { mode: "timestamp_ms" })`;
    case "json":
      used.add("text");
      return `text(${json(col)}, { mode: "json" })`;
    default:
      throw unknownKind(field.kind, col);
  }
}

function emitPostgresBase(col: string, field: AnyFieldDef, used: Set<string>): string {
  switch (field.kind) {
    case "string":
      used.add("text");
      return `text(${json(col)})`;
    case "number":
      if ((field as { integer?: boolean }).integer === true) {
        used.add("integer");
        return `integer(${json(col)})`;
      }
      used.add("real");
      return `real(${json(col)})`;
    case "boolean":
      used.add("boolean");
      return `boolean(${json(col)})`;
    case "date":
      used.add("date");
      return `date(${json(col)}, { mode: "string" })`;
    case "datetime":
      used.add("timestamp");
      return `timestamp(${json(col)}, { withTimezone: true, mode: "date" })`;
    case "json":
      used.add("jsonb");
      return `jsonb(${json(col)})`;
    default:
      throw unknownKind(field.kind, col);
  }
}

function applyMods(base: string, field: AnyFieldDef): string {
  let out = base;
  if (field.required) out += `.notNull()`;
  if (field.unique) out += `.unique()`;
  return out;
}

function unknownKind(kind: string, name: string): Error {
  return new Error(
    `writeDrizzleBridge: unknown field kind "${kind}" for column "${name}". Custom fields must map to a known column type.`,
  );
}

/** Same camelCase → snake_case conversion `schemaToTables` uses. */
function toColumnName(name: string): string {
  return name.replace(/[A-Z]/g, (c) => `_${c.toLowerCase()}`);
}

/* ---------------------------------------------------------------- file io */

function json(v: string): string {
  return JSON.stringify(v);
}

function writeIfChanged(file: string, contents: string): void {
  if (existsSync(file) && readFileSync(file, "utf8") === contents) return;
  writeFileSync(file, contents);
}

/**
 * Default location of the generated bridge file, relative to `cwd`. Lives in
 * `drizzle/` to mirror drizzle-kit's own conventions and to keep it adjacent
 * to the `migrations/` output dir.
 */
export const DEFAULT_BRIDGE_PATH = "drizzle/schema.gen.ts";

export function resolveBridgePath(cwd: string, override?: string): string {
  return resolve(cwd, override ?? DEFAULT_BRIDGE_PATH);
}
