/**
 * `/admin/login` — the only admin route that's reachable without a session.
 * Generated by the vite plugin alongside the other admin pages so the
 * branding stays in sync with `content.config.ts`.
 */
export function adminLoginSource(configImport: string): string {
  return `import { createFileRoute } from "@tanstack/react-router";
import { LoginView } from "@voila/content/internal";
import content from "${configImport}";

function search(input: Record<string, unknown>): { next?: string } {
  const next = typeof input.next === "string" ? input.next : undefined;
  return { next };
}

export const Route = createFileRoute("/admin/login")({
  validateSearch: search,
  component: RouteComponent,
});

function RouteComponent() {
  const { next } = Route.useSearch();
  return <LoginView config={content} next={next ?? "/admin"} />;
}
`;
}
