/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AppSplatRouteImport } from './routes/_app.$'
import { Route as AppCollectionIndexRouteImport } from './routes/_app.$collection.index'
import { Route as AppCollectionNewRouteImport } from './routes/_app.$collection.new'
import { Route as AppCollectionIdRouteImport } from './routes/_app.$collection.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionIndexRoute = AppCollectionIndexRouteImport.update({
  id: '/$collection/',
  path: '/$collection/',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionNewRoute = AppCollectionNewRouteImport.update({
  id: '/$collection/new',
  path: '/$collection/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionIdRoute = AppCollectionIdRouteImport.update({
  id: '/$collection/$id',
  path: '/$collection/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/$collection/$id': typeof AppCollectionIdRoute
  '/$collection/new': typeof AppCollectionNewRoute
  '/$collection/': typeof AppCollectionIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof AppIndexRoute
  '/$collection/$id': typeof AppCollectionIdRoute
  '/$collection/new': typeof AppCollectionNewRoute
  '/$collection': typeof AppCollectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/$': typeof AppSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/$collection/$id': typeof AppCollectionIdRoute
  '/_app/$collection/new': typeof AppCollectionNewRoute
  '/_app/$collection/': typeof AppCollectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$'
    | '/api/$'
    | '/$collection/$id'
    | '/$collection/new'
    | '/$collection/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$'
    | '/api/$'
    | '/'
    | '/$collection/$id'
    | '/$collection/new'
    | '/$collection'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/$'
    | '/api/$'
    | '/_app/'
    | '/_app/$collection/$id'
    | '/_app/$collection/new'
    | '/_app/$collection/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$collection/': {
      id: '/_app/$collection/'
      path: '/$collection'
      fullPath: '/$collection/'
      preLoaderRoute: typeof AppCollectionIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$collection/new': {
      id: '/_app/$collection/new'
      path: '/$collection/new'
      fullPath: '/$collection/new'
      preLoaderRoute: typeof AppCollectionNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$collection/$id': {
      id: '/_app/$collection/$id'
      path: '/$collection/$id'
      fullPath: '/$collection/$id'
      preLoaderRoute: typeof AppCollectionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCollectionIdRoute: typeof AppCollectionIdRoute
  AppCollectionNewRoute: typeof AppCollectionNewRoute
  AppCollectionIndexRoute: typeof AppCollectionIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppIndexRoute: AppIndexRoute,
  AppCollectionIdRoute: AppCollectionIdRoute,
  AppCollectionNewRoute: AppCollectionNewRoute,
  AppCollectionIndexRoute: AppCollectionIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
