import { createRouter as createTanStackRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

// `routeTree.gen` is generated by the TanStack Start plugin from the files under
// `app/routes` — run `vite dev` (or `vite build`) once and it appears. The
// not-found screen lives on the root route so it renders inside the site shell.
export function getRouter() {
  return createTanStackRouter({
    routeTree,
    scrollRestoration: true,
    defaultPreload: "intent",
  });
}
