/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminPostsIndexRouteImport } from './routes/admin.posts.index'
import { Route as AdminPostsNewRouteImport } from './routes/admin.posts.new'
import { Route as AdminPostsIdRouteImport } from './routes/admin.posts.$id'
import { Route as AdminApiSplatRouteImport } from './routes/admin.api.$'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiSplatRoute = AdminApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/api/$': typeof AdminApiSplatRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/api/$': typeof AdminApiSplatRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/posts': typeof AdminPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin_/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/api/$': typeof AdminApiSplatRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/'
    | '/admin/api/$'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/admin/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/admin'
    | '/admin/api/$'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/admin/posts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin_/login'
    | '/admin/'
    | '/admin/api/$'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/admin/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/posts/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api/$': {
      id: '/admin/api/$'
      path: '/api/$'
      fullPath: '/admin/api/$'
      preLoaderRoute: typeof AdminApiSplatRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminApiSplatRoute: typeof AdminApiSplatRoute
  AdminPostsIdRoute: typeof AdminPostsIdRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminApiSplatRoute: AdminApiSplatRoute,
  AdminPostsIdRoute: AdminPostsIdRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
